services:
  - type: web
    name: pingme-backend
    rootDir: backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node src/server.js"

  - type: web
    name: pingme-frontend
    rootDir: frontend
    env: static
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
